package ua.org.dector.uCompiler.lex_demo;

/**
 * @author dector (dector9@gmail.com)
 */
public enum Position {
    START, FINISHED,

    ACCUMULATE_IDENTIFIER, ACCUMULATE_STRING, ACCUMULATE_OPERATOR, ACCUMULATE_DECIMAL_NUMBER,
    ACCUMULATE_REAL_NUMBER,

    NEW_IDENTIFIER_TOKEN, NEW_KEYWORD_TOKEN, NEW_STRING_TOKEN, NEW_OPERATOR_TOKEN, NEW_DELIMITER_TOKEN,
    NEW_DECIMAL_NUMBER_TOKEN, NEW_REAL_NUMBER_TOKEN,

    CHECK_KEYWORD, CHECK_OPERATOR, SUCCESS_CHECK, DETECT_STRING,

    IDENTIFIER_ERROR, OPERATOR_ERROR, DECIMAL_NUMBER_ERROR, REAL_NUMBER_ERROR,

    UNDEFINED_INPUT_ERROR, UNEXPECTED_END_OF_FILE_ERROR,

    IO_EXCEPTION
}
